[package]
name = 'CoinList'
version = '0.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = '5b0ae7fbea9623e4042c2ef288801a6e44d3d75c'
subdir = 'aptos-move/framework/aptos-framework'


[addresses]
coin_list = "498d8926f16eb9ca90cab1b3a26aa6f97a080b3fcbe6e83ae150b7243a00fb68"
